package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setTrueName(java.lang.String trueName) {
		set("true_name", trueName);
	}

	public java.lang.String getTrueName() {
		return get("true_name");
	}

	public void setCreateOperater(java.lang.String createOperater) {
		set("create_operater", createOperater);
	}

	public java.lang.String getCreateOperater() {
		return get("create_operater");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setOperateTime(java.util.Date operateTime) {
		set("operate_time", operateTime);
	}

	public java.util.Date getOperateTime() {
		return get("operate_time");
	}

	public void setLastModifyOperater(java.lang.String lastModifyOperater) {
		set("last_modify_operater", lastModifyOperater);
	}

	public java.lang.String getLastModifyOperater() {
		return get("last_modify_operater");
	}

	public void setLastModifyTime(java.util.Date lastModifyTime) {
		set("last_modify_time", lastModifyTime);
	}

	public java.util.Date getLastModifyTime() {
		return get("last_modify_time");
	}

	public void setLastModifyTime1(java.util.Date lastModifyTime1) {
		set("last_modify_time1", lastModifyTime1);
	}

	public java.util.Date getLastModifyTime1() {
		return get("last_modify_time1");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setEmployeeId(java.lang.Long employeeId) {
		set("employee_id", employeeId);
	}

	public java.lang.Long getEmployeeId() {
		return get("employee_id");
	}

}
