package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProMeter<M extends BaseProMeter<M>> extends Model<M> implements IBean {

	public void setMeterId(java.lang.Long meterId) {
		set("meter_id", meterId);
	}

	public java.lang.Long getMeterId() {
		return get("meter_id");
	}

	public void setMeterNum(java.lang.String meterNum) {
		set("meter_num", meterNum);
	}

	public java.lang.String getMeterNum() {
		return get("meter_num");
	}

	public void setMeterName(java.lang.String meterName) {
		set("meter_name", meterName);
	}

	public java.lang.String getMeterName() {
		return get("meter_name");
	}

	public void setMeterSpec(java.lang.Integer meterSpec) {
		set("meter_spec", meterSpec);
	}

	public java.lang.Integer getMeterSpec() {
		return get("meter_spec");
	}

	public void setMeterType(java.lang.Integer meterType) {
		set("meter_type", meterType);
	}

	public java.lang.Integer getMeterType() {
		return get("meter_type");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setHouseId(java.lang.Long houseId) {
		set("house_id", houseId);
	}

	public java.lang.Long getHouseId() {
		return get("house_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}

	public java.lang.Integer getIsShare() {
		return get("is_share");
	}

	public void setRoomType(java.lang.String roomType) {
		set("room_type", roomType);
	}

	public java.lang.String getRoomType() {
		return get("room_type");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setMeterModel(java.lang.Integer meterModel) {
		set("meter_model", meterModel);
	}

	public java.lang.Integer getMeterModel() {
		return get("meter_model");
	}

	public void setRatedVoltage(java.lang.Double ratedVoltage) {
		set("rated_voltage", ratedVoltage);
	}

	public java.lang.Double getRatedVoltage() {
		return get("rated_voltage");
	}

	public void setRate(java.lang.Double rate) {
		set("rate", rate);
	}

	public java.lang.Double getRate() {
		return get("rate");
	}

	public void setInstallDate(java.util.Date installDate) {
		set("install_date", installDate);
	}

	public java.util.Date getInstallDate() {
		return get("install_date");
	}

	public void setInstallCount(java.lang.Double installCount) {
		set("install_count", installCount);
	}

	public java.lang.Double getInstallCount() {
		return get("install_count");
	}

	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}

	public java.lang.String getAmount() {
		return get("amount");
	}

	public void setStopDate(java.util.Date stopDate) {
		set("stop_date", stopDate);
	}

	public java.util.Date getStopDate() {
		return get("stop_date");
	}

	public void setMeterOperPer(java.lang.String meterOperPer) {
		set("meter_oper_per", meterOperPer);
	}

	public java.lang.String getMeterOperPer() {
		return get("meter_oper_per");
	}

	public void setMeterBook(java.lang.String meterBook) {
		set("meter_book", meterBook);
	}

	public java.lang.String getMeterBook() {
		return get("meter_book");
	}

	public void setMeterOrder(java.lang.Integer meterOrder) {
		set("meter_order", meterOrder);
	}

	public java.lang.Integer getMeterOrder() {
		return get("meter_order");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setWaterMeterType(java.lang.Integer waterMeterType) {
		set("water_meter_type", waterMeterType);
	}

	public java.lang.Integer getWaterMeterType() {
		return get("water_meter_type");
	}

	public void setMId(java.lang.Long mId) {
		set("m_id", mId);
	}

	public java.lang.Long getMId() {
		return get("m_id");
	}

	public void setBarcode(java.lang.String barcode) {
		set("barcode", barcode);
	}

	public java.lang.String getBarcode() {
		return get("barcode");
	}

	public void setMeterFeeType(java.lang.Integer meterFeeType) {
		set("meter_fee_type", meterFeeType);
	}

	public java.lang.Integer getMeterFeeType() {
		return get("meter_fee_type");
	}

	public void setMinimumDosage(java.lang.String minimumDosage) {
		set("minimum_dosage", minimumDosage);
	}

	public java.lang.String getMinimumDosage() {
		return get("minimum_dosage");
	}

	public void setLossRatio(java.lang.String lossRatio) {
		set("loss_ratio", lossRatio);
	}

	public java.lang.String getLossRatio() {
		return get("loss_ratio");
	}

}
