package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinTradeSummary<M extends BaseFinTradeSummary<M>> extends Model<M> implements IBean {

	public void setTradeBatchNo(java.lang.String tradeBatchNo) {
		set("trade_batch_no", tradeBatchNo);
	}

	public java.lang.String getTradeBatchNo() {
		return get("trade_batch_no");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setUseOwnerId(java.lang.Long useOwnerId) {
		set("use_owner_id", useOwnerId);
	}

	public java.lang.Long getUseOwnerId() {
		return get("use_owner_id");
	}

	public void setIsOwner(java.lang.Integer isOwner) {
		set("is_owner", isOwner);
	}

	public java.lang.Integer getIsOwner() {
		return get("is_owner");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setPrepaidAccountId(java.lang.Long prepaidAccountId) {
		set("prepaid_account_id", prepaidAccountId);
	}

	public java.lang.Long getPrepaidAccountId() {
		return get("prepaid_account_id");
	}

	public void setChargeName(java.lang.String chargeName) {
		set("charge_name", chargeName);
	}

	public java.lang.String getChargeName() {
		return get("charge_name");
	}

	public void setChargeCardNo(java.lang.String chargeCardNo) {
		set("charge_card_no", chargeCardNo);
	}

	public java.lang.String getChargeCardNo() {
		return get("charge_card_no");
	}

	public void setChargeBankName(java.lang.String chargeBankName) {
		set("charge_bank_name", chargeBankName);
	}

	public java.lang.String getChargeBankName() {
		return get("charge_bank_name");
	}

	public void setBatchReceiveAmount(java.math.BigDecimal batchReceiveAmount) {
		set("batch_receive_amount", batchReceiveAmount);
	}

	public java.math.BigDecimal getBatchReceiveAmount() {
		return get("batch_receive_amount");
	}

	public void setBatchPreferentialAmount(java.math.BigDecimal batchPreferentialAmount) {
		set("batch_preferential_amount", batchPreferentialAmount);
	}

	public java.math.BigDecimal getBatchPreferentialAmount() {
		return get("batch_preferential_amount");
	}

	public void setBatchPayAmount(java.math.BigDecimal batchPayAmount) {
		set("batch_pay_amount", batchPayAmount);
	}

	public java.math.BigDecimal getBatchPayAmount() {
		return get("batch_pay_amount");
	}

	public void setOverdueAmount(java.math.BigDecimal overdueAmount) {
		set("overdue_amount", overdueAmount);
	}

	public java.math.BigDecimal getOverdueAmount() {
		return get("overdue_amount");
	}

	public void setBankPoundage(java.math.BigDecimal bankPoundage) {
		set("bank_poundage", bankPoundage);
	}

	public java.math.BigDecimal getBankPoundage() {
		return get("bank_poundage");
	}

	public void setChargeItemCount(java.lang.Integer chargeItemCount) {
		set("charge_item_count", chargeItemCount);
	}

	public java.lang.Integer getChargeItemCount() {
		return get("charge_item_count");
	}

	public void setChargeStatus(java.lang.Integer chargeStatus) {
		set("charge_status", chargeStatus);
	}

	public java.lang.Integer getChargeStatus() {
		return get("charge_status");
	}

	public void setChargeType(java.lang.Long chargeType) {
		set("charge_type", chargeType);
	}

	public java.lang.Long getChargeType() {
		return get("charge_type");
	}

	public void setArrearageStatus(java.lang.Integer arrearageStatus) {
		set("arrearage_status", arrearageStatus);
	}

	public java.lang.Integer getArrearageStatus() {
		return get("arrearage_status");
	}

	public void setAccountDate(java.util.Date accountDate) {
		set("account_date", accountDate);
	}

	public java.util.Date getAccountDate() {
		return get("account_date");
	}

	public void setExecStatus(java.lang.Integer execStatus) {
		set("exec_status", execStatus);
	}

	public java.lang.Integer getExecStatus() {
		return get("exec_status");
	}

	public void setExecTime(java.util.Date execTime) {
		set("exec_time", execTime);
	}

	public java.util.Date getExecTime() {
		return get("exec_time");
	}

	public void setExecResult(java.lang.String execResult) {
		set("exec_result", execResult);
	}

	public java.lang.String getExecResult() {
		return get("exec_result");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
	}

	public java.lang.Integer getAuditStatus() {
		return get("audit_status");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setExtType(java.lang.Integer extType) {
		set("ext_type", extType);
	}

	public java.lang.Integer getExtType() {
		return get("ext_type");
	}

	public void setDkTradeNo(java.lang.String dkTradeNo) {
		set("dk_trade_no", dkTradeNo);
	}

	public java.lang.String getDkTradeNo() {
		return get("dk_trade_no");
	}

}
