package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoomCharge<M extends BaseRoomCharge<M>> extends Model<M> implements IBean {

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setHouseId(java.lang.Long houseId) {
		set("house_id", houseId);
	}

	public java.lang.Long getHouseId() {
		return get("house_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setQuota(java.math.BigDecimal quota) {
		set("quota", quota);
	}

	public java.math.BigDecimal getQuota() {
		return get("quota");
	}

	public void setMonth(java.lang.Integer month) {
		set("month", month);
	}

	public java.lang.Integer getMonth() {
		return get("month");
	}

	public void setRentalStartIncrease(java.util.Date rentalStartIncrease) {
		set("rental_start_increase", rentalStartIncrease);
	}

	public java.util.Date getRentalStartIncrease() {
		return get("rental_start_increase");
	}

	public void setRentalIncreasePeriod(java.lang.Long rentalIncreasePeriod) {
		set("rental_increase_period", rentalIncreasePeriod);
	}

	public java.lang.Long getRentalIncreasePeriod() {
		return get("rental_increase_period");
	}

	public void setRentalIncreaseRatio(java.lang.Double rentalIncreaseRatio) {
		set("rental_increase_ratio", rentalIncreaseRatio);
	}

	public java.lang.Double getRentalIncreaseRatio() {
		return get("rental_increase_ratio");
	}

	public void setAuditPer(java.lang.String auditPer) {
		set("audit_per", auditPer);
	}

	public java.lang.String getAuditPer() {
		return get("audit_per");
	}

	public void setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
	}

	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperId(java.lang.Long operId) {
		set("oper_id", operId);
	}

	public java.lang.Long getOperId() {
		return get("oper_id");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setAdministrativeFee(java.math.BigDecimal administrativeFee) {
		set("administrative_fee", administrativeFee);
	}

	public java.math.BigDecimal getAdministrativeFee() {
		return get("administrative_fee");
	}

	public void setPreferential(java.math.BigDecimal preferential) {
		set("preferential", preferential);
	}

	public java.math.BigDecimal getPreferential() {
		return get("preferential");
	}

	public void setPreferentialDateBegin(java.util.Date preferentialDateBegin) {
		set("preferential_date_begin", preferentialDateBegin);
	}

	public java.util.Date getPreferentialDateBegin() {
		return get("preferential_date_begin");
	}

	public void setPreferentialDateEnd(java.util.Date preferentialDateEnd) {
		set("preferential_date_end", preferentialDateEnd);
	}

	public java.util.Date getPreferentialDateEnd() {
		return get("preferential_date_end");
	}

}
