package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarCard<M extends BaseCarCard<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCardNum(java.lang.String cardNum) {
		set("card_num", cardNum);
	}

	public java.lang.String getCardNum() {
		return get("card_num");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setIcard(java.lang.String icard) {
		set("icard", icard);
	}

	public java.lang.String getIcard() {
		return get("icard");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
	}

	public java.lang.String getCarNumber() {
		return get("car_number");
	}

	public void setCarType(java.lang.String carType) {
		set("car_type", carType);
	}

	public java.lang.String getCarType() {
		return get("car_type");
	}

	public void setCarBrand(java.lang.String carBrand) {
		set("car_brand", carBrand);
	}

	public java.lang.String getCarBrand() {
		return get("car_brand");
	}

	public void setCarColour(java.lang.String carColour) {
		set("car_colour", carColour);
	}

	public java.lang.String getCarColour() {
		return get("car_colour");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

	public void setCardStatus(java.lang.String cardStatus) {
		set("card_status", cardStatus);
	}

	public java.lang.String getCardStatus() {
		return get("card_status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
	}

	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.Integer getSequence() {
		return get("sequence");
	}

	public void setTruckSpacNum(java.lang.String truckSpacNum) {
		set("truck_spac_num", truckSpacNum);
	}

	public java.lang.String getTruckSpacNum() {
		return get("truck_spac_num");
	}

}
