package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinTradeDetail<M extends BaseFinTradeDetail<M>> extends Model<M> implements IBean {

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public void setTradeBatchNo(java.lang.String tradeBatchNo) {
		set("trade_batch_no", tradeBatchNo);
	}

	public java.lang.String getTradeBatchNo() {
		return get("trade_batch_no");
	}

	public void setAccount(java.lang.Double account) {
		set("account", account);
	}

	public java.lang.Double getAccount() {
		return get("account");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setReceiveAmount(java.math.BigDecimal receiveAmount) {
		set("receive_amount", receiveAmount);
	}

	public java.math.BigDecimal getReceiveAmount() {
		return get("receive_amount");
	}

	public void setPreferentialAmount(java.math.BigDecimal preferentialAmount) {
		set("preferential_amount", preferentialAmount);
	}

	public java.math.BigDecimal getPreferentialAmount() {
		return get("preferential_amount");
	}

	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("pay_amount", payAmount);
	}

	public java.math.BigDecimal getPayAmount() {
		return get("pay_amount");
	}

	public void setPayCashAmount(java.math.BigDecimal payCashAmount) {
		set("pay_cash_amount", payCashAmount);
	}

	public java.math.BigDecimal getPayCashAmount() {
		return get("pay_cash_amount");
	}

	public void setPayPosAmount(java.math.BigDecimal payPosAmount) {
		set("pay_pos_amount", payPosAmount);
	}

	public java.math.BigDecimal getPayPosAmount() {
		return get("pay_pos_amount");
	}

	public void setOverdueAmount(java.math.BigDecimal overdueAmount) {
		set("overdue_amount", overdueAmount);
	}

	public java.math.BigDecimal getOverdueAmount() {
		return get("overdue_amount");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setChargeDetailId(java.lang.Long chargeDetailId) {
		set("charge_detail_id", chargeDetailId);
	}

	public java.lang.Long getChargeDetailId() {
		return get("charge_detail_id");
	}

	public void setChargeStartDate(java.util.Date chargeStartDate) {
		set("charge_start_date", chargeStartDate);
	}

	public java.util.Date getChargeStartDate() {
		return get("charge_start_date");
	}

	public void setChargeEndDate(java.util.Date chargeEndDate) {
		set("charge_end_date", chargeEndDate);
	}

	public java.util.Date getChargeEndDate() {
		return get("charge_end_date");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setUseOwnerId(java.lang.Long useOwnerId) {
		set("use_owner_id", useOwnerId);
	}

	public java.lang.Long getUseOwnerId() {
		return get("use_owner_id");
	}

	public void setIsOwner(java.lang.Integer isOwner) {
		set("is_owner", isOwner);
	}

	public java.lang.Integer getIsOwner() {
		return get("is_owner");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setExtType(java.lang.Integer extType) {
		set("ext_type", extType);
	}

	public java.lang.Integer getExtType() {
		return get("ext_type");
	}

	public void setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
	}

	public java.lang.Integer getAuditStatus() {
		return get("audit_status");
	}

	public void setAuditUserId(java.lang.Long auditUserId) {
		set("audit_user_id", auditUserId);
	}

	public java.lang.Long getAuditUserId() {
		return get("audit_user_id");
	}

	public void setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
	}

	public java.util.Date getAuditTime() {
		return get("audit_time");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setPayType(java.lang.Long payType) {
		set("pay_type", payType);
	}

	public java.lang.Long getPayType() {
		return get("pay_type");
	}

	public void setReceiptNum(java.lang.String receiptNum) {
		set("receipt_num", receiptNum);
	}

	public java.lang.String getReceiptNum() {
		return get("receipt_num");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setCancelUserId(java.lang.Long cancelUserId) {
		set("cancel_user_id", cancelUserId);
	}

	public java.lang.Long getCancelUserId() {
		return get("cancel_user_id");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	public void setCancelRemark(java.lang.String cancelRemark) {
		set("cancel_remark", cancelRemark);
	}

	public java.lang.String getCancelRemark() {
		return get("cancel_remark");
	}

	public void setCancelReceiptNum(java.lang.String cancelReceiptNum) {
		set("cancel_receipt_num", cancelReceiptNum);
	}

	public java.lang.String getCancelReceiptNum() {
		return get("cancel_receipt_num");
	}

	public void setPrintTimes(java.lang.Integer printTimes) {
		set("print_times", printTimes);
	}

	public java.lang.Integer getPrintTimes() {
		return get("print_times");
	}

	public void setExtValue(java.lang.String extValue) {
		set("ext_value", extValue);
	}

	public java.lang.String getExtValue() {
		return get("ext_value");
	}

	public void setPayEndDate(java.util.Date payEndDate) {
		set("pay_end_date", payEndDate);
	}

	public java.util.Date getPayEndDate() {
		return get("pay_end_date");
	}

	public void setRefundUserId(java.lang.Integer refundUserId) {
		set("refund_user_id", refundUserId);
	}

	public java.lang.Integer getRefundUserId() {
		return get("refund_user_id");
	}

	public void setRefundStatus(java.lang.Integer refundStatus) {
		set("refund_status", refundStatus);
	}

	public java.lang.Integer getRefundStatus() {
		return get("refund_status");
	}

	public void setRefundDate(java.util.Date refundDate) {
		set("refund_date", refundDate);
	}

	public java.util.Date getRefundDate() {
		return get("refund_date");
	}

	public void setUnitNum(java.lang.String unitNum) {
		set("unit_num", unitNum);
	}

	public java.lang.String getUnitNum() {
		return get("unit_num");
	}

	public void setCheckDate(java.util.Date checkDate) {
		set("check_date", checkDate);
	}

	public java.util.Date getCheckDate() {
		return get("check_date");
	}

	public void setZhuhuNum(java.lang.String zhuhuNum) {
		set("zhuhu_num", zhuhuNum);
	}

	public java.lang.String getZhuhuNum() {
		return get("zhuhu_num");
	}

	public void setLinkYehu(java.lang.String linkYehu) {
		set("link_yehu", linkYehu);
	}

	public java.lang.String getLinkYehu() {
		return get("link_yehu");
	}

	public void setJfId(java.lang.Long jfId) {
		set("jf_id", jfId);
	}

	public java.lang.Long getJfId() {
		return get("jf_id");
	}

	public void setAuditName(java.lang.String auditName) {
		set("audit_name", auditName);
	}

	public java.lang.String getAuditName() {
		return get("audit_name");
	}

	public void setRechecker(java.lang.String rechecker) {
		set("rechecker", rechecker);
	}

	public java.lang.String getRechecker() {
		return get("rechecker");
	}

	public void setRecheckDate(java.util.Date recheckDate) {
		set("recheck_date", recheckDate);
	}

	public java.util.Date getRecheckDate() {
		return get("recheck_date");
	}

	public void setRecheckerId(java.lang.Long recheckerId) {
		set("rechecker_id", recheckerId);
	}

	public java.lang.Long getRecheckerId() {
		return get("rechecker_id");
	}

	public void setCancelName(java.lang.String cancelName) {
		set("cancel_name", cancelName);
	}

	public java.lang.String getCancelName() {
		return get("cancel_name");
	}

	public void setRunStatus(java.lang.Integer runStatus) {
		set("run_status", runStatus);
	}

	public java.lang.Integer getRunStatus() {
		return get("run_status");
	}

}
