package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOptMerchant<M extends BaseOptMerchant<M>> extends Model<M> implements IBean {

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setMerName(java.lang.String merName) {
		set("mer_name", merName);
	}

	public java.lang.String getMerName() {
		return get("mer_name");
	}

	public void setMerAddress(java.lang.String merAddress) {
		set("mer_address", merAddress);
	}

	public java.lang.String getMerAddress() {
		return get("mer_address");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setLegal(java.lang.String legal) {
		set("legal", legal);
	}

	public java.lang.String getLegal() {
		return get("legal");
	}

	public void setCerImg(java.lang.String cerImg) {
		set("cer_img", cerImg);
	}

	public java.lang.String getCerImg() {
		return get("cer_img");
	}

	public void setLinkman(java.lang.String linkman) {
		set("linkman", linkman);
	}

	public java.lang.String getLinkman() {
		return get("linkman");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setMerType(java.lang.Integer merType) {
		set("mer_type", merType);
	}

	public java.lang.Integer getMerType() {
		return get("mer_type");
	}

	public void setHasPraking(java.lang.Integer hasPraking) {
		set("has_praking", hasPraking);
	}

	public java.lang.Integer getHasPraking() {
		return get("has_praking");
	}

	public void setEpayAccount(java.lang.String epayAccount) {
		set("epay_account", epayAccount);
	}

	public java.lang.String getEpayAccount() {
		return get("epay_account");
	}

	public void setEpayMerchantId(java.lang.String epayMerchantId) {
		set("epay_merchant_id", epayMerchantId);
	}

	public java.lang.String getEpayMerchantId() {
		return get("epay_merchant_id");
	}

	public void setEpayMerchantSecret(java.lang.String epayMerchantSecret) {
		set("epay_merchant_secret", epayMerchantSecret);
	}

	public java.lang.String getEpayMerchantSecret() {
		return get("epay_merchant_secret");
	}

	public void setSmsChannelId(java.lang.Long smsChannelId) {
		set("sms_channel_id", smsChannelId);
	}

	public java.lang.Long getSmsChannelId() {
		return get("sms_channel_id");
	}

	public void setSmsMerchantId(java.lang.String smsMerchantId) {
		set("sms_merchant_id", smsMerchantId);
	}

	public java.lang.String getSmsMerchantId() {
		return get("sms_merchant_id");
	}

	public void setSmsMerchantPwd(java.lang.String smsMerchantPwd) {
		set("sms_merchant_pwd", smsMerchantPwd);
	}

	public java.lang.String getSmsMerchantPwd() {
		return get("sms_merchant_pwd");
	}

	public void setSmsCount(java.lang.Long smsCount) {
		set("sms_count", smsCount);
	}

	public java.lang.Long getSmsCount() {
		return get("sms_count");
	}

	public void setSmsModifyTime(java.util.Date smsModifyTime) {
		set("sms_modify_time", smsModifyTime);
	}

	public java.util.Date getSmsModifyTime() {
		return get("sms_modify_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setOptUserId(java.lang.Long optUserId) {
		set("opt_user_id", optUserId);
	}

	public java.lang.Long getOptUserId() {
		return get("opt_user_id");
	}

	public void setOptName(java.lang.String optName) {
		set("opt_name", optName);
	}

	public java.lang.String getOptName() {
		return get("opt_name");
	}

}
