package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaterElecRac<M extends BaseWaterElecRac<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setWaterMeterId(java.lang.Long waterMeterId) {
		set("water_meter_id", waterMeterId);
	}

	public java.lang.Long getWaterMeterId() {
		return get("water_meter_id");
	}

	public void setElecMeterId(java.lang.Long elecMeterId) {
		set("elec_meter_id", elecMeterId);
	}

	public java.lang.Long getElecMeterId() {
		return get("elec_meter_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
