package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderRefund<M extends BaseOrderRefund<M>> extends Model<M> implements IBean {

	public void setFefundId(java.lang.Long fefundId) {
		set("fefund_id", fefundId);
	}

	public java.lang.Long getFefundId() {
		return get("fefund_id");
	}

	public void setFefundNo(java.lang.String fefundNo) {
		set("fefund_no", fefundNo);
	}

	public java.lang.String getFefundNo() {
		return get("fefund_no");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setPayAmount(java.math.BigDecimal payAmount) {
		set("pay_amount", payAmount);
	}

	public java.math.BigDecimal getPayAmount() {
		return get("pay_amount");
	}

	public void setFefundDate(java.util.Date fefundDate) {
		set("fefund_date", fefundDate);
	}

	public java.util.Date getFefundDate() {
		return get("fefund_date");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setExecStatus(java.lang.Integer execStatus) {
		set("exec_status", execStatus);
	}

	public java.lang.Integer getExecStatus() {
		return get("exec_status");
	}

	public void setExecTime(java.util.Date execTime) {
		set("exec_time", execTime);
	}

	public java.util.Date getExecTime() {
		return get("exec_time");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setExecResult(java.lang.String execResult) {
		set("exec_result", execResult);
	}

	public java.lang.String getExecResult() {
		return get("exec_result");
	}

}
