package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShareRule<M extends BaseShareRule<M>> extends Model<M> implements IBean {

	public void setShareRuleId(java.lang.Long shareRuleId) {
		set("share_rule_id", shareRuleId);
	}

	public java.lang.Long getShareRuleId() {
		return get("share_rule_id");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setShareRuleName(java.lang.String shareRuleName) {
		set("share_rule_name", shareRuleName);
	}

	public java.lang.String getShareRuleName() {
		return get("share_rule_name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
	}

	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}

	public java.lang.Integer getEnable() {
		return get("enable");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
