package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsRecord<M extends BaseSmsRecord<M>> extends Model<M> implements IBean {

	public void setSmsRecordId(java.lang.Long smsRecordId) {
		set("sms_record_id", smsRecordId);
	}

	public java.lang.Long getSmsRecordId() {
		return get("sms_record_id");
	}

	public void setSmsType(java.lang.Integer smsType) {
		set("sms_type", smsType);
	}

	public java.lang.Integer getSmsType() {
		return get("sms_type");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setSmsContent(java.lang.String smsContent) {
		set("sms_content", smsContent);
	}

	public java.lang.String getSmsContent() {
		return get("sms_content");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setIsTiming(java.lang.Boolean isTiming) {
		set("is_timing", isTiming);
	}

	public java.lang.Boolean getIsTiming() {
		return get("is_timing");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setTiming(java.util.Date timing) {
		set("timing", timing);
	}

	public java.util.Date getTiming() {
		return get("timing");
	}

	public void setOperPer(java.lang.Long operPer) {
		set("oper_per", operPer);
	}

	public java.lang.Long getOperPer() {
		return get("oper_per");
	}

	public void setSmsTemplateId(java.lang.Long smsTemplateId) {
		set("sms_template_id", smsTemplateId);
	}

	public java.lang.Long getSmsTemplateId() {
		return get("sms_template_id");
	}

	public void setPoundage(java.math.BigDecimal poundage) {
		set("poundage", poundage);
	}

	public java.math.BigDecimal getPoundage() {
		return get("poundage");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

}
