package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoomRentUpdate<M extends BaseRoomRentUpdate<M>> extends Model<M> implements IBean {

	public void setRoomRentUpdateId(java.lang.Long roomRentUpdateId) {
		set("room_rent_update_id", roomRentUpdateId);
	}

	public java.lang.Long getRoomRentUpdateId() {
		return get("room_rent_update_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setBeforeAmount(java.math.BigDecimal beforeAmount) {
		set("before_amount", beforeAmount);
	}

	public java.math.BigDecimal getBeforeAmount() {
		return get("before_amount");
	}

	public void setNowAmount(java.math.BigDecimal nowAmount) {
		set("now_amount", nowAmount);
	}

	public java.math.BigDecimal getNowAmount() {
		return get("now_amount");
	}

	public void setUpdateRate(java.math.BigDecimal updateRate) {
		set("update_rate", updateRate);
	}

	public java.math.BigDecimal getUpdateRate() {
		return get("update_rate");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
