package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinBankAccount<M extends BaseFinBankAccount<M>> extends Model<M> implements IBean {

	public void setBankAccountId(java.lang.Long bankAccountId) {
		set("bank_account_id", bankAccountId);
	}

	public java.lang.Long getBankAccountId() {
		return get("bank_account_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setCashBalance(java.math.BigDecimal cashBalance) {
		set("cash_balance", cashBalance);
	}

	public java.math.BigDecimal getCashBalance() {
		return get("cash_balance");
	}

	public void setFrozenBalance(java.math.BigDecimal frozenBalance) {
		set("frozen_balance", frozenBalance);
	}

	public java.math.BigDecimal getFrozenBalance() {
		return get("frozen_balance");
	}

}
