package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysChart<M extends BaseSysChart<M>> extends Model<M> implements IBean {

	public void setChartId(java.lang.Long chartId) {
		set("chart_id", chartId);
	}

	public java.lang.Long getChartId() {
		return get("chart_id");
	}

	public void setChartNum(java.lang.String chartNum) {
		set("chart_num", chartNum);
	}

	public java.lang.String getChartNum() {
		return get("chart_num");
	}

	public void setChartName(java.lang.String chartName) {
		set("chart_name", chartName);
	}

	public java.lang.String getChartName() {
		return get("chart_name");
	}

	public void setRoleIds(java.lang.String roleIds) {
		set("role_ids", roleIds);
	}

	public java.lang.String getRoleIds() {
		return get("role_ids");
	}

	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}

	public java.lang.Integer getEnable() {
		return get("enable");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
