package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleMenu<M extends BaseSysRoleMenu<M>> extends Model<M> implements IBean {

	public void setRoleMenuId(java.lang.Long roleMenuId) {
		set("role_menu_id", roleMenuId);
	}

	public java.lang.Long getRoleMenuId() {
		return get("role_menu_id");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("role_id");
	}

	public void setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
	}

	public java.lang.Long getMenuId() {
		return get("menu_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
