package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServiceOrder<M extends BaseServiceOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setRoomNo(java.lang.String roomNo) {
		set("room_no", roomNo);
	}

	public java.lang.String getRoomNo() {
		return get("room_no");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
	}

	public java.lang.String getContactName() {
		return get("contact_name");
	}

	public void setContactMobile(java.lang.String contactMobile) {
		set("contact_mobile", contactMobile);
	}

	public java.lang.String getContactMobile() {
		return get("contact_mobile");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
	}

	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

	public void setBespeakTime(java.util.Date bespeakTime) {
		set("bespeak_time", bespeakTime);
	}

	public java.util.Date getBespeakTime() {
		return get("bespeak_time");
	}

	public void setServiceType(java.lang.String serviceType) {
		set("service_type", serviceType);
	}

	public java.lang.String getServiceType() {
		return get("service_type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public void setCheckUser(java.lang.String checkUser) {
		set("check_user", checkUser);
	}

	public java.lang.String getCheckUser() {
		return get("check_user");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCompletionStatus(java.lang.Integer completionStatus) {
		set("completion_status", completionStatus);
	}

	public java.lang.Integer getCompletionStatus() {
		return get("completion_status");
	}

	public void setSatisfactionStatus(java.lang.Integer satisfactionStatus) {
		set("satisfaction_status", satisfactionStatus);
	}

	public java.lang.Integer getSatisfactionStatus() {
		return get("satisfaction_status");
	}

	public void setReturningUser(java.lang.String returningUser) {
		set("returning_user", returningUser);
	}

	public java.lang.String getReturningUser() {
		return get("returning_user");
	}

	public void setReeturningTime(java.util.Date reeturningTime) {
		set("reeturning_time", reeturningTime);
	}

	public java.util.Date getReeturningTime() {
		return get("reeturning_time");
	}

	public void setEmpName(java.lang.String empName) {
		set("emp_name", empName);
	}

	public java.lang.String getEmpName() {
		return get("emp_name");
	}

	public void setDepName(java.lang.String depName) {
		set("dep_name", depName);
	}

	public java.lang.String getDepName() {
		return get("dep_name");
	}

	public void setEmpId(java.lang.Long empId) {
		set("emp_id", empId);
	}

	public java.lang.Long getEmpId() {
		return get("emp_id");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setPayPepoleId(java.lang.Long payPepoleId) {
		set("pay_pepole_id", payPepoleId);
	}

	public java.lang.Long getPayPepoleId() {
		return get("pay_pepole_id");
	}

	public void setPayPeople(java.lang.String payPeople) {
		set("pay_people", payPeople);
	}

	public java.lang.String getPayPeople() {
		return get("pay_people");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setChargeType(java.lang.Long chargeType) {
		set("charge_type", chargeType);
	}

	public java.lang.Long getChargeType() {
		return get("charge_type");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

}
