package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProGuestextend<M extends BaseProGuestextend<M>> extends Model<M> implements IBean {

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public void setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
	}

	public java.lang.String getBankCode() {
		return get("bank_code");
	}

	public void setBankCardName(java.lang.String bankCardName) {
		set("bank_card_name", bankCardName);
	}

	public java.lang.String getBankCardName() {
		return get("bank_card_name");
	}

	public void setBankCredNo(java.lang.String bankCredNo) {
		set("bank_cred_no", bankCredNo);
	}

	public java.lang.String getBankCredNo() {
		return get("bank_cred_no");
	}

	public void setBankCardMobile(java.lang.String bankCardMobile) {
		set("bank_card_mobile", bankCardMobile);
	}

	public java.lang.String getBankCardMobile() {
		return get("bank_card_mobile");
	}

	public void setJobUnit(java.lang.String jobUnit) {
		set("job_unit", jobUnit);
	}

	public java.lang.String getJobUnit() {
		return get("job_unit");
	}

	public void setJobName(java.lang.String jobName) {
		set("job_name", jobName);
	}

	public java.lang.String getJobName() {
		return get("job_name");
	}

	public void setCarNo(java.lang.String carNo) {
		set("car_no", carNo);
	}

	public java.lang.String getCarNo() {
		return get("car_no");
	}

	public void setContactPer(java.lang.String contactPer) {
		set("contact_per", contactPer);
	}

	public java.lang.String getContactPer() {
		return get("contact_per");
	}

	public void setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
	}

	public java.lang.String getContactPhone() {
		return get("contact_phone");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setAutoPay(java.lang.Integer autoPay) {
		set("auto_pay", autoPay);
	}

	public java.lang.Integer getAutoPay() {
		return get("auto_pay");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}

	public java.lang.Integer getGrade() {
		return get("grade");
	}

}
