package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOptConfig<M extends BaseOptConfig<M>> extends Model<M> implements IBean {

	public void setConfigId(java.lang.Long configId) {
		set("config_id", configId);
	}

	public java.lang.Long getConfigId() {
		return get("config_id");
	}

	public void setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
	}

	public java.lang.Long getGroupId() {
		return get("group_id");
	}

	public void setCfgName(java.lang.String cfgName) {
		set("cfg_name", cfgName);
	}

	public java.lang.String getCfgName() {
		return get("cfg_name");
	}

	public void setCfgKey(java.lang.String cfgKey) {
		set("cfg_key", cfgKey);
	}

	public java.lang.String getCfgKey() {
		return get("cfg_key");
	}

	public void setCfgValue(java.lang.String cfgValue) {
		set("cfg_value", cfgValue);
	}

	public java.lang.String getCfgValue() {
		return get("cfg_value");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setReqStatus(java.lang.Integer reqStatus) {
		set("req_status", reqStatus);
	}

	public java.lang.Integer getReqStatus() {
		return get("req_status");
	}

}
