package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProHouse<M extends BaseProHouse<M>> extends Model<M> implements IBean {

	public void setHouseId(java.lang.Long houseId) {
		set("house_id", houseId);
	}

	public java.lang.Long getHouseId() {
		return get("house_id");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setHouseNum(java.lang.String houseNum) {
		set("house_num", houseNum);
	}

	public java.lang.String getHouseNum() {
		return get("house_num");
	}

	public void setHouseName(java.lang.String houseName) {
		set("house_name", houseName);
	}

	public java.lang.String getHouseName() {
		return get("house_name");
	}

	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}

	public java.lang.Integer getIsShare() {
		return get("is_share");
	}

	public void setHouseAddress(java.lang.String houseAddress) {
		set("house_address", houseAddress);
	}

	public java.lang.String getHouseAddress() {
		return get("house_address");
	}

	public void setHouseFloor(java.lang.Integer houseFloor) {
		set("house_floor", houseFloor);
	}

	public java.lang.Integer getHouseFloor() {
		return get("house_floor");
	}

	public void setRoomNum(java.lang.Integer roomNum) {
		set("room_num", roomNum);
	}

	public java.lang.Integer getRoomNum() {
		return get("room_num");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setHouseSort(java.lang.Integer houseSort) {
		set("house_sort", houseSort);
	}

	public java.lang.Integer getHouseSort() {
		return get("house_sort");
	}

}
