package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinPrepayCharge<M extends BaseFinPrepayCharge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setRechargeRecordId(java.lang.Long rechargeRecordId) {
		set("recharge_record_id", rechargeRecordId);
	}

	public java.lang.Long getRechargeRecordId() {
		return get("recharge_record_id");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setTariff(java.lang.Integer tariff) {
		set("tariff", tariff);
	}

	public java.lang.Integer getTariff() {
		return get("tariff");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}

	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setTariffMoney(java.math.BigDecimal tariffMoney) {
		set("tariff_money", tariffMoney);
	}

	public java.math.BigDecimal getTariffMoney() {
		return get("tariff_money");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setDeductionsAmount(java.math.BigDecimal deductionsAmount) {
		set("deductions_amount", deductionsAmount);
	}

	public java.math.BigDecimal getDeductionsAmount() {
		return get("deductions_amount");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

}
