package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarAttachment<M extends BaseCarAttachment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCardId(java.lang.Long cardId) {
		set("card_id", cardId);
	}

	public java.lang.Long getCardId() {
		return get("card_id");
	}

	public void setAttaName(java.lang.String attaName) {
		set("atta_name", attaName);
	}

	public java.lang.String getAttaName() {
		return get("atta_name");
	}

	public void setAttaUrl(java.lang.String attaUrl) {
		set("atta_url", attaUrl);
	}

	public java.lang.String getAttaUrl() {
		return get("atta_url");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
