package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProContract<M extends BaseProContract<M>> extends Model<M> implements IBean {

	public void setContractId(java.lang.Long contractId) {
		set("contract_id", contractId);
	}

	public java.lang.Long getContractId() {
		return get("contract_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setContractNum(java.lang.String contractNum) {
		set("contract_num", contractNum);
	}

	public java.lang.String getContractNum() {
		return get("contract_num");
	}

	public void setContractStatus(java.lang.Integer contractStatus) {
		set("contract_status", contractStatus);
	}

	public java.lang.Integer getContractStatus() {
		return get("contract_status");
	}

	public void setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
	}

	public java.util.Date getSignDate() {
		return get("sign_date");
	}

	public void setHireDate(java.util.Date hireDate) {
		set("hire_date", hireDate);
	}

	public java.util.Date getHireDate() {
		return get("hire_date");
	}

	public void setUprentDate(java.util.Date uprentDate) {
		set("uprent_date", uprentDate);
	}

	public java.util.Date getUprentDate() {
		return get("uprent_date");
	}

	public void setHireYear(java.lang.Long hireYear) {
		set("hire_year", hireYear);
	}

	public java.lang.Long getHireYear() {
		return get("hire_year");
	}

	public void setFitmentCost(java.lang.Double fitmentCost) {
		set("fitment_cost", fitmentCost);
	}

	public java.lang.Double getFitmentCost() {
		return get("fitment_cost");
	}

	public void setReservationsNum(java.lang.String reservationsNum) {
		set("reservations_num", reservationsNum);
	}

	public java.lang.String getReservationsNum() {
		return get("reservations_num");
	}

	public void setRental(java.lang.String rental) {
		set("rental", rental);
	}

	public java.lang.String getRental() {
		return get("rental");
	}

	public void setDeposit(java.lang.String deposit) {
		set("deposit", deposit);
	}

	public java.lang.String getDeposit() {
		return get("deposit");
	}

	public void setPaymentCycle(java.lang.String paymentCycle) {
		set("payment_cycle", paymentCycle);
	}

	public java.lang.String getPaymentCycle() {
		return get("payment_cycle");
	}

	public void setContractTemplateId(java.lang.Long contractTemplateId) {
		set("contract_template_id", contractTemplateId);
	}

	public java.lang.Long getContractTemplateId() {
		return get("contract_template_id");
	}

	public void setSupplementId(java.lang.Long supplementId) {
		set("supplement_id", supplementId);
	}

	public java.lang.Long getSupplementId() {
		return get("supplement_id");
	}

	public void setContractType(java.lang.Integer contractType) {
		set("contract_type", contractType);
	}

	public java.lang.Integer getContractType() {
		return get("contract_type");
	}

	public void setSupplementalAgreementNum(java.lang.String supplementalAgreementNum) {
		set("supplemental_agreement_num", supplementalAgreementNum);
	}

	public java.lang.String getSupplementalAgreementNum() {
		return get("supplemental_agreement_num");
	}

	public void setUseWay(java.lang.String useWay) {
		set("use_way", useWay);
	}

	public java.lang.String getUseWay() {
		return get("use_way");
	}

	public void setContractChangeNum(java.lang.String contractChangeNum) {
		set("contract_change_num", contractChangeNum);
	}

	public java.lang.String getContractChangeNum() {
		return get("contract_change_num");
	}

	public void setIsAttach(java.lang.Integer isAttach) {
		set("is_attach", isAttach);
	}

	public java.lang.Integer getIsAttach() {
		return get("is_attach");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.Long operPer) {
		set("oper_per", operPer);
	}

	public java.lang.Long getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setAuditPer(java.lang.Long auditPer) {
		set("audit_per", auditPer);
	}

	public java.lang.Long getAuditPer() {
		return get("audit_per");
	}

	public void setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
	}

	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public void setTerminationPer(java.lang.Long terminationPer) {
		set("termination_per", terminationPer);
	}

	public java.lang.Long getTerminationPer() {
		return get("termination_per");
	}

	public void setTerminationDate(java.util.Date terminationDate) {
		set("termination_date", terminationDate);
	}

	public java.util.Date getTerminationDate() {
		return get("termination_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setContractFile(byte[] contractFile) {
		set("contract_file", contractFile);
	}

	public byte[] getContractFile() {
		return get("contract_file");
	}

	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}

	public java.lang.String getFilePath() {
		return get("file_path");
	}

	public void setSmsStatus(java.lang.Integer smsStatus) {
		set("sms_status", smsStatus);
	}

	public java.lang.Integer getSmsStatus() {
		return get("sms_status");
	}

	public void setExt1(java.lang.String ext1) {
		set("ext1", ext1);
	}

	public java.lang.String getExt1() {
		return get("ext1");
	}

	public void setExt2(java.lang.String ext2) {
		set("ext2", ext2);
	}

	public java.lang.String getExt2() {
		return get("ext2");
	}

	public void setExt3(java.lang.String ext3) {
		set("ext3", ext3);
	}

	public java.lang.String getExt3() {
		return get("ext3");
	}

	public void setExt4(java.lang.Integer ext4) {
		set("ext4", ext4);
	}

	public java.lang.Integer getExt4() {
		return get("ext4");
	}

	public void setTerminationReason(java.lang.String terminationReason) {
		set("termination_reason", terminationReason);
	}

	public java.lang.String getTerminationReason() {
		return get("termination_reason");
	}

}
