package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogOperation<M extends BaseLogOperation<M>> extends Model<M> implements IBean {

	public void setLogId(java.lang.Long logId) {
		set("log_id", logId);
	}

	public java.lang.Long getLogId() {
		return get("log_id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCallFrom(java.lang.Integer callFrom) {
		set("call_from", callFrom);
	}

	public java.lang.Integer getCallFrom() {
		return get("call_from");
	}

	public void setMenu(java.lang.String menu) {
		set("menu", menu);
	}

	public java.lang.String getMenu() {
		return get("menu");
	}

	public void setFunc(java.lang.String func) {
		set("func", func);
	}

	public java.lang.String getFunc() {
		return get("func");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setSystemRemark(java.lang.String systemRemark) {
		set("system_remark", systemRemark);
	}

	public java.lang.String getSystemRemark() {
		return get("system_remark");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setClientIp(java.lang.String clientIp) {
		set("client_ip", clientIp);
	}

	public java.lang.String getClientIp() {
		return get("client_ip");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
