package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProEmployee<M extends BaseProEmployee<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setEmpNum(java.lang.String empNum) {
		set("emp_num", empNum);
	}

	public java.lang.String getEmpNum() {
		return get("emp_num");
	}

	public void setEmpName(java.lang.String empName) {
		set("emp_name", empName);
	}

	public java.lang.String getEmpName() {
		return get("emp_name");
	}

	public void setEmpSex(java.lang.String empSex) {
		set("emp_sex", empSex);
	}

	public java.lang.String getEmpSex() {
		return get("emp_sex");
	}

	public void setWorkStatus(java.lang.String workStatus) {
		set("work_status", workStatus);
	}

	public java.lang.String getWorkStatus() {
		return get("work_status");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

	public java.lang.String getIdentity() {
		return get("identity");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("role_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDepartmentId(java.lang.Long departmentId) {
		set("department_id", departmentId);
	}

	public java.lang.Long getDepartmentId() {
		return get("department_id");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setEmpImage(java.lang.String empImage) {
		set("emp_image", empImage);
	}

	public java.lang.String getEmpImage() {
		return get("emp_image");
	}

}
