package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarInOut<M extends BaseCarInOut<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCardNo(java.lang.Long cardNo) {
		set("card_no", cardNo);
	}

	public java.lang.Long getCardNo() {
		return get("card_no");
	}

	public void setCardType(java.lang.String cardType) {
		set("card_type", cardType);
	}

	public java.lang.String getCardType() {
		return get("card_type");
	}

	public void setEmplNo(java.lang.String emplNo) {
		set("empl_no", emplNo);
	}

	public java.lang.String getEmplNo() {
		return get("empl_no");
	}

	public void setCardName(java.lang.String cardName) {
		set("card_name", cardName);
	}

	public java.lang.String getCardName() {
		return get("card_name");
	}

	public void setComeName(java.lang.String comeName) {
		set("come_name", comeName);
	}

	public java.lang.String getComeName() {
		return get("come_name");
	}

	public void setOperNo(java.lang.String operNo) {
		set("oper_no", operNo);
	}

	public java.lang.String getOperNo() {
		return get("oper_no");
	}

	public void setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
	}

	public java.lang.String getCarNumber() {
		return get("car_number");
	}

	public void setInOutTime(java.util.Date inOutTime) {
		set("in_out_time", inOutTime);
	}

	public java.util.Date getInOutTime() {
		return get("in_out_time");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public void setGarageId(java.lang.Long garageId) {
		set("garage_id", garageId);
	}

	public java.lang.Long getGarageId() {
		return get("garage_id");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setMDate(java.util.Date mDate) {
		set("m_date", mDate);
	}

	public java.util.Date getMDate() {
		return get("m_date");
	}

	public void setMMno(java.lang.String mMno) {
		set("m_mno", mMno);
	}

	public java.lang.String getMMno() {
		return get("m_mno");
	}

	public void setTimeOutMoney(java.math.BigDecimal timeOutMoney) {
		set("time_out_money", timeOutMoney);
	}

	public java.math.BigDecimal getTimeOutMoney() {
		return get("time_out_money");
	}

	public void setTimeOutDate(java.util.Date timeOutDate) {
		set("time_out_date", timeOutDate);
	}

	public java.util.Date getTimeOutDate() {
		return get("time_out_date");
	}

	public void setOutMoneyNo(java.lang.String outMoneyNo) {
		set("out_money_no", outMoneyNo);
	}

	public java.lang.String getOutMoneyNo() {
		return get("out_money_no");
	}

	public void setBigSmall(java.lang.Integer bigSmall) {
		set("big_small", bigSmall);
	}

	public java.lang.Integer getBigSmall() {
		return get("big_small");
	}

	public void setPapPic(java.lang.String papPic) {
		set("pap_pic", papPic);
	}

	public java.lang.String getPapPic() {
		return get("pap_pic");
	}

	public void setFMoney(java.math.BigDecimal fMoney) {
		set("f_money", fMoney);
	}

	public java.math.BigDecimal getFMoney() {
		return get("f_money");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCardMoney(java.math.BigDecimal cardMoney) {
		set("card_money", cardMoney);
	}

	public java.math.BigDecimal getCardMoney() {
		return get("card_money");
	}

	public void setBMoney(java.math.BigDecimal bMoney) {
		set("b_money", bMoney);
	}

	public java.math.BigDecimal getBMoney() {
		return get("b_money");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

}
