package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysNotice<M extends BaseSysNotice<M>> extends Model<M> implements IBean {

	public void setNoticeId(java.lang.Long noticeId) {
		set("notice_id", noticeId);
	}

	public java.lang.Long getNoticeId() {
		return get("notice_id");
	}

	public void setNoticeName(java.lang.String noticeName) {
		set("notice_name", noticeName);
	}

	public java.lang.String getNoticeName() {
		return get("notice_name");
	}

	public void setNoticeType(java.lang.Integer noticeType) {
		set("notice_type", noticeType);
	}

	public java.lang.Integer getNoticeType() {
		return get("notice_type");
	}

	public void setNoticeText(java.lang.String noticeText) {
		set("notice_text", noticeText);
	}

	public java.lang.String getNoticeText() {
		return get("notice_text");
	}

	public void setNoticeTime(java.util.Date noticeTime) {
		set("notice_time", noticeTime);
	}

	public java.util.Date getNoticeTime() {
		return get("notice_time");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

}
