package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarGarage<M extends BaseCarGarage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setGarageNum(java.lang.String garageNum) {
		set("garage_num", garageNum);
	}

	public java.lang.String getGarageNum() {
		return get("garage_num");
	}

	public void setGarageName(java.lang.String garageName) {
		set("garage_name", garageName);
	}

	public java.lang.String getGarageName() {
		return get("garage_name");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setSurplusNumber(java.lang.Integer surplusNumber) {
		set("surplus_number", surplusNumber);
	}

	public java.lang.Integer getSurplusNumber() {
		return get("surplus_number");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
