package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinTradeOverdue<M extends BaseFinTradeOverdue<M>> extends Model<M> implements IBean {

	public void setTradeOverdueId(java.lang.Long tradeOverdueId) {
		set("trade_overdue_id", tradeOverdueId);
	}

	public java.lang.Long getTradeOverdueId() {
		return get("trade_overdue_id");
	}

	public void setTradeDetailId(java.lang.Long tradeDetailId) {
		set("trade_detail_id", tradeDetailId);
	}

	public java.lang.Long getTradeDetailId() {
		return get("trade_detail_id");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setChargeDetailId(java.lang.Long chargeDetailId) {
		set("charge_detail_id", chargeDetailId);
	}

	public java.lang.Long getChargeDetailId() {
		return get("charge_detail_id");
	}

	public void setCombineTradeDetailId(java.lang.Long combineTradeDetailId) {
		set("combine_trade_detail_id", combineTradeDetailId);
	}

	public java.lang.Long getCombineTradeDetailId() {
		return get("combine_trade_detail_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setUseOwnerId(java.lang.Long useOwnerId) {
		set("use_owner_id", useOwnerId);
	}

	public java.lang.Long getUseOwnerId() {
		return get("use_owner_id");
	}

	public void setIsOwner(java.lang.Integer isOwner) {
		set("is_owner", isOwner);
	}

	public java.lang.Integer getIsOwner() {
		return get("is_owner");
	}

	public void setNeedPayAmount(java.math.BigDecimal needPayAmount) {
		set("need_pay_amount", needPayAmount);
	}

	public java.math.BigDecimal getNeedPayAmount() {
		return get("need_pay_amount");
	}

	public void setChargeEndDate(java.util.Date chargeEndDate) {
		set("charge_end_date", chargeEndDate);
	}

	public java.util.Date getChargeEndDate() {
		return get("charge_end_date");
	}

	public void setCreatDate(java.util.Date creatDate) {
		set("creat_date", creatDate);
	}

	public java.util.Date getCreatDate() {
		return get("creat_date");
	}

	public void setOverdueDays(java.lang.Integer overdueDays) {
		set("overdue_days", overdueDays);
	}

	public java.lang.Integer getOverdueDays() {
		return get("overdue_days");
	}

	public void setOverdueAmount(java.math.BigDecimal overdueAmount) {
		set("overdue_amount", overdueAmount);
	}

	public java.math.BigDecimal getOverdueAmount() {
		return get("overdue_amount");
	}

	public void setOverdueRate(java.math.BigDecimal overdueRate) {
		set("overdue_rate", overdueRate);
	}

	public java.math.BigDecimal getOverdueRate() {
		return get("overdue_rate");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCombineTime(java.util.Date combineTime) {
		set("combine_time", combineTime);
	}

	public java.util.Date getCombineTime() {
		return get("combine_time");
	}

	public void setChargeTime(java.util.Date chargeTime) {
		set("charge_time", chargeTime);
	}

	public java.util.Date getChargeTime() {
		return get("charge_time");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
