package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinSubject<M extends BaseFinSubject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSubNo(java.lang.String subNo) {
		set("sub_no", subNo);
	}

	public java.lang.String getSubNo() {
		return get("sub_no");
	}

	public void setPSubNo(java.lang.String pSubNo) {
		set("p_sub_no", pSubNo);
	}

	public java.lang.String getPSubNo() {
		return get("p_sub_no");
	}

	public void setSubName(java.lang.String subName) {
		set("sub_name", subName);
	}

	public java.lang.String getSubName() {
		return get("sub_name");
	}

	public void setSubType(java.lang.Integer subType) {
		set("sub_type", subType);
	}

	public java.lang.Integer getSubType() {
		return get("sub_type");
	}

	public void setBalDire(java.lang.String balDire) {
		set("bal_dire", balDire);
	}

	public java.lang.String getBalDire() {
		return get("bal_dire");
	}

	public void setEffectiveDate(java.util.Date effectiveDate) {
		set("effective_date", effectiveDate);
	}

	public java.util.Date getEffectiveDate() {
		return get("effective_date");
	}

	public void setInvalidDate(java.util.Date invalidDate) {
		set("invalid_date", invalidDate);
	}

	public java.util.Date getInvalidDate() {
		return get("invalid_date");
	}

	public void setSonItem(java.lang.String sonItem) {
		set("son_item", sonItem);
	}

	public java.lang.String getSonItem() {
		return get("son_item");
	}

	public void setSpecificItem(java.lang.String specificItem) {
		set("specific_item", specificItem);
	}

	public java.lang.String getSpecificItem() {
		return get("specific_item");
	}

	public void setManualKeepAccounts(java.lang.String manualKeepAccounts) {
		set("manual_keep_accounts", manualKeepAccounts);
	}

	public java.lang.String getManualKeepAccounts() {
		return get("manual_keep_accounts");
	}

	public void setChargeNum(java.lang.String chargeNum) {
		set("charge_num", chargeNum);
	}

	public java.lang.String getChargeNum() {
		return get("charge_num");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIsEnable(java.lang.String isEnable) {
		set("is_enable", isEnable);
	}

	public java.lang.String getIsEnable() {
		return get("is_enable");
	}

}
