package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProRoomDeposit<M extends BaseProRoomDeposit<M>> extends Model<M> implements IBean {

	public void setRoomDepositId(java.lang.Long roomDepositId) {
		set("room_deposit_id", roomDepositId);
	}

	public java.lang.Long getRoomDepositId() {
		return get("room_deposit_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setRoomType(java.lang.String roomType) {
		set("room_type", roomType);
	}

	public java.lang.String getRoomType() {
		return get("room_type");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setSubAmount(java.math.BigDecimal subAmount) {
		set("sub_amount", subAmount);
	}

	public java.math.BigDecimal getSubAmount() {
		return get("sub_amount");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setExecStatus(java.lang.Integer execStatus) {
		set("exec_status", execStatus);
	}

	public java.lang.Integer getExecStatus() {
		return get("exec_status");
	}

	public void setPayType(java.lang.Long payType) {
		set("pay_type", payType);
	}

	public java.lang.Long getPayType() {
		return get("pay_type");
	}

	public void setExecResult(java.lang.String execResult) {
		set("exec_result", execResult);
	}

	public java.lang.String getExecResult() {
		return get("exec_result");
	}

	public void setExecTime(java.util.Date execTime) {
		set("exec_time", execTime);
	}

	public java.util.Date getExecTime() {
		return get("exec_time");
	}

	public void setDepositType(java.lang.String depositType) {
		set("deposit_type", depositType);
	}

	public java.lang.String getDepositType() {
		return get("deposit_type");
	}

	public void setRoomDepositType(java.lang.Integer roomDepositType) {
		set("room_deposit_type", roomDepositType);
	}

	public java.lang.Integer getRoomDepositType() {
		return get("room_deposit_type");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setReviewed(java.lang.String reviewed) {
		set("reviewed", reviewed);
	}

	public java.lang.String getReviewed() {
		return get("reviewed");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setReceiptNumber(java.lang.String receiptNumber) {
		set("receipt_number", receiptNumber);
	}

	public java.lang.String getReceiptNumber() {
		return get("receipt_number");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}

	public java.lang.String getTarget() {
		return get("target");
	}

	public void setTargetType(java.lang.Integer targetType) {
		set("target_type", targetType);
	}

	public java.lang.Integer getTargetType() {
		return get("target_type");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setHouseId(java.lang.Long houseId) {
		set("house_id", houseId);
	}

	public java.lang.Long getHouseId() {
		return get("house_id");
	}

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setRefundDate(java.util.Date refundDate) {
		set("refund_date", refundDate);
	}

	public java.util.Date getRefundDate() {
		return get("refund_date");
	}

	public void setOriginalNum(java.lang.String originalNum) {
		set("original_num", originalNum);
	}

	public java.lang.String getOriginalNum() {
		return get("original_num");
	}

	public void setRefundRemark(java.lang.String refundRemark) {
		set("refund_remark", refundRemark);
	}

	public java.lang.String getRefundRemark() {
		return get("refund_remark");
	}

}
