package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("role_id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

	public java.lang.String getRoleName() {
		return get("role_name");
	}

	public void setCreateOperater(java.lang.String createOperater) {
		set("create_operater", createOperater);
	}

	public java.lang.String getCreateOperater() {
		return get("create_operater");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setOperateTime(java.util.Date operateTime) {
		set("operate_time", operateTime);
	}

	public java.util.Date getOperateTime() {
		return get("operate_time");
	}

	public void setRoleSign(java.lang.String roleSign) {
		set("role_sign", roleSign);
	}

	public java.lang.String getRoleSign() {
		return get("role_sign");
	}

	public void setType(java.lang.Long type) {
		set("type", type);
	}

	public java.lang.Long getType() {
		return get("type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
