package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProRoom<M extends BaseProRoom<M>> extends Model<M> implements IBean {

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setRoomOrderNum(java.lang.Double roomOrderNum) {
		set("room_order_num", roomOrderNum);
	}

	public java.lang.Double getRoomOrderNum() {
		return get("room_order_num");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setHouseId(java.lang.Long houseId) {
		set("house_id", houseId);
	}

	public java.lang.Long getHouseId() {
		return get("house_id");
	}

	public void setRoomNum(java.lang.String roomNum) {
		set("room_num", roomNum);
	}

	public java.lang.String getRoomNum() {
		return get("room_num");
	}

	public void setLeaseStatus(java.lang.Integer leaseStatus) {
		set("lease_status", leaseStatus);
	}

	public java.lang.Integer getLeaseStatus() {
		return get("lease_status");
	}

	public void setRoomType(java.lang.String roomType) {
		set("room_type", roomType);
	}

	public java.lang.String getRoomType() {
		return get("room_type");
	}

	public void setProperty(java.lang.Integer property) {
		set("property", property);
	}

	public java.lang.Integer getProperty() {
		return get("property");
	}

	public void setBuildingArea(java.math.BigDecimal buildingArea) {
		set("building_area", buildingArea);
	}

	public java.math.BigDecimal getBuildingArea() {
		return get("building_area");
	}

	public void setActualArea(java.lang.Double actualArea) {
		set("actual_area", actualArea);
	}

	public java.lang.Double getActualArea() {
		return get("actual_area");
	}

	public void setShareArea(java.lang.Double shareArea) {
		set("share_area", shareArea);
	}

	public java.lang.Double getShareArea() {
		return get("share_area");
	}

	public void setRental(java.math.BigDecimal rental) {
		set("rental", rental);
	}

	public java.math.BigDecimal getRental() {
		return get("rental");
	}

	public void setFloor(java.lang.Integer floor) {
		set("floor", floor);
	}

	public java.lang.Integer getFloor() {
		return get("floor");
	}

	public void setUnitNum(java.lang.Integer unitNum) {
		set("unit_num", unitNum);
	}

	public java.lang.Integer getUnitNum() {
		return get("unit_num");
	}

	public void setDirection(java.lang.String direction) {
		set("direction", direction);
	}

	public java.lang.String getDirection() {
		return get("direction");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setDecorationSituation(java.lang.String decorationSituation) {
		set("decoration_situation", decorationSituation);
	}

	public java.lang.String getDecorationSituation() {
		return get("decoration_situation");
	}

	public void setPurpose(java.lang.String purpose) {
		set("purpose", purpose);
	}

	public java.lang.String getPurpose() {
		return get("purpose");
	}

	public void setServicePer(java.lang.String servicePer) {
		set("service_per", servicePer);
	}

	public java.lang.String getServicePer() {
		return get("service_per");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setTmpOwnerNum(java.lang.String tmpOwnerNum) {
		set("tmp_owner_num", tmpOwnerNum);
	}

	public java.lang.String getTmpOwnerNum() {
		return get("tmp_owner_num");
	}

	public void setIsOverdue(java.lang.Integer isOverdue) {
		set("is_overdue", isOverdue);
	}

	public java.lang.Integer getIsOverdue() {
		return get("is_overdue");
	}

}
