package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMsCrdbinInf<M extends BaseMsCrdbinInf<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setIssnam(java.lang.String issnam) {
		set("issnam", issnam);
	}

	public java.lang.String getIssnam() {
		return get("issnam");
	}

	public void setIssno(java.lang.String issno) {
		set("issno", issno);
	}

	public java.lang.String getIssno() {
		return get("issno");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
	}

	public java.lang.String getBankCode() {
		return get("bank_code");
	}

	public void setIsEnable(java.lang.Integer isEnable) {
		set("is_enable", isEnable);
	}

	public java.lang.Integer getIsEnable() {
		return get("is_enable");
	}

}
