package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProManagement<M extends BaseProManagement<M>> extends Model<M> implements IBean {

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setManageNum(java.lang.String manageNum) {
		set("manage_num", manageNum);
	}

	public java.lang.String getManageNum() {
		return get("manage_num");
	}

	public void setManageName(java.lang.String manageName) {
		set("manage_name", manageName);
	}

	public java.lang.String getManageName() {
		return get("manage_name");
	}

	public void setManageAddress(java.lang.String manageAddress) {
		set("manage_address", manageAddress);
	}

	public java.lang.String getManageAddress() {
		return get("manage_address");
	}

	public void setBuildingArea(java.lang.Double buildingArea) {
		set("building_area", buildingArea);
	}

	public java.lang.Double getBuildingArea() {
		return get("building_area");
	}

	public void setGreenArea(java.lang.Double greenArea) {
		set("green_area", greenArea);
	}

	public java.lang.Double getGreenArea() {
		return get("green_area");
	}

	public void setGarageArea(java.lang.Double garageArea) {
		set("garage_area", garageArea);
	}

	public java.lang.Double getGarageArea() {
		return get("garage_area");
	}

	public void setGarageNum(java.lang.Integer garageNum) {
		set("garage_num", garageNum);
	}

	public java.lang.Integer getGarageNum() {
		return get("garage_num");
	}

	public void setResponsiblePer(java.lang.String responsiblePer) {
		set("responsible_per", responsiblePer);
	}

	public java.lang.String getResponsiblePer() {
		return get("responsible_per");
	}

	public void setContactPer(java.lang.String contactPer) {
		set("contact_per", contactPer);
	}

	public java.lang.String getContactPer() {
		return get("contact_per");
	}

	public void setContactPhone(java.lang.String contactPhone) {
		set("contact_phone", contactPhone);
	}

	public java.lang.String getContactPhone() {
		return get("contact_phone");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
