package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShareRecord<M extends BaseShareRecord<M>> extends Model<M> implements IBean {

	public void setBatchNo(java.lang.String batchNo) {
		set("batch_no", batchNo);
	}

	public java.lang.String getBatchNo() {
		return get("batch_no");
	}

	public void setManageId(java.lang.Long manageId) {
		set("manage_id", manageId);
	}

	public java.lang.Long getManageId() {
		return get("manage_id");
	}

	public void setShareAmountSelf(java.math.BigDecimal shareAmountSelf) {
		set("share_amount_self", shareAmountSelf);
	}

	public java.math.BigDecimal getShareAmountSelf() {
		return get("share_amount_self");
	}

	public void setShareAmountOther(java.math.BigDecimal shareAmountOther) {
		set("share_amount_other", shareAmountOther);
	}

	public java.math.BigDecimal getShareAmountOther() {
		return get("share_amount_other");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
