package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinPrepaidAccount<M extends BaseFinPrepaidAccount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setPrepaidId(java.lang.String prepaidId) {
		set("prepaid_id", prepaidId);
	}

	public java.lang.String getPrepaidId() {
		return get("prepaid_id");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setGuestId(java.lang.Long guestId) {
		set("guest_id", guestId);
	}

	public java.lang.Long getGuestId() {
		return get("guest_id");
	}

	public void setRoomId(java.lang.Long roomId) {
		set("room_id", roomId);
	}

	public java.lang.Long getRoomId() {
		return get("room_id");
	}

	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}

	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public void setAccountStatus(java.lang.Integer accountStatus) {
		set("account_status", accountStatus);
	}

	public java.lang.Integer getAccountStatus() {
		return get("account_status");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setPayDate(java.util.Date payDate) {
		set("pay_date", payDate);
	}

	public java.util.Date getPayDate() {
		return get("pay_date");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setTax(java.math.BigDecimal tax) {
		set("tax", tax);
	}

	public java.math.BigDecimal getTax() {
		return get("tax");
	}

	public void setTariffMoney(java.math.BigDecimal tariffMoney) {
		set("tariff_money", tariffMoney);
	}

	public java.math.BigDecimal getTariffMoney() {
		return get("tariff_money");
	}

	public void setDeductionsAmount(java.math.BigDecimal deductionsAmount) {
		set("deductions_amount", deductionsAmount);
	}

	public java.math.BigDecimal getDeductionsAmount() {
		return get("deductions_amount");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setChargeAmount(java.math.BigDecimal chargeAmount) {
		set("charge_amount", chargeAmount);
	}

	public java.math.BigDecimal getChargeAmount() {
		return get("charge_amount");
	}

}
