package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProDepartment<M extends BaseProDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setDepId(java.lang.Long depId) {
		set("dep_id", depId);
	}

	public java.lang.Long getDepId() {
		return get("dep_id");
	}

	public void setDepName(java.lang.String depName) {
		set("dep_name", depName);
	}

	public java.lang.String getDepName() {
		return get("dep_name");
	}

	public void setDepRemarks(java.lang.String depRemarks) {
		set("dep_remarks", depRemarks);
	}

	public java.lang.String getDepRemarks() {
		return get("dep_remarks");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setTopParentId(java.lang.Integer topParentId) {
		set("top_parent_id", topParentId);
	}

	public java.lang.Integer getTopParentId() {
		return get("top_parent_id");
	}

}
