package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPayment<M extends BaseSysPayment<M>> extends Model<M> implements IBean {

	public void setPaymentId(java.lang.Long paymentId) {
		set("payment_id", paymentId);
	}

	public java.lang.Long getPaymentId() {
		return get("payment_id");
	}

	public void setPaymentNum(java.lang.String paymentNum) {
		set("payment_num", paymentNum);
	}

	public java.lang.String getPaymentNum() {
		return get("payment_num");
	}

	public void setPaymentName(java.lang.String paymentName) {
		set("payment_name", paymentName);
	}

	public java.lang.String getPaymentName() {
		return get("payment_name");
	}

	public void setRoleIds(java.lang.String roleIds) {
		set("role_ids", roleIds);
	}

	public java.lang.String getRoleIds() {
		return get("role_ids");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setSortIndex(java.lang.Integer sortIndex) {
		set("sort_index", sortIndex);
	}

	public java.lang.Integer getSortIndex() {
		return get("sort_index");
	}

	public void setIsEnable(java.lang.Integer isEnable) {
		set("is_enable", isEnable);
	}

	public java.lang.Integer getIsEnable() {
		return get("is_enable");
	}

	public void setExtValue(java.lang.String extValue) {
		set("ext_value", extValue);
	}

	public java.lang.String getExtValue() {
		return get("ext_value");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
