package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBankOffer<M extends BaseBankOffer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
	}

	public java.lang.String getBankCode() {
		return get("bank_code");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setIsEnable(java.lang.Integer isEnable) {
		set("is_enable", isEnable);
	}

	public java.lang.Integer getIsEnable() {
		return get("is_enable");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.String proId) {
		set("pro_id", proId);
	}

	public java.lang.String getProId() {
		return get("pro_id");
	}

}
