package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProGuestbase<M extends BaseProGuestbase<M>> extends Model<M> implements IBean {

	public void setOwnerId(java.lang.Long ownerId) {
		set("owner_id", ownerId);
	}

	public java.lang.Long getOwnerId() {
		return get("owner_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public void setOwnerType(java.lang.Integer ownerType) {
		set("owner_type", ownerType);
	}

	public java.lang.Integer getOwnerType() {
		return get("owner_type");
	}

	public void setOwnerName(java.lang.String ownerName) {
		set("owner_name", ownerName);
	}

	public java.lang.String getOwnerName() {
		return get("owner_name");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setAppPwd(java.lang.String appPwd) {
		set("app_pwd", appPwd);
	}

	public java.lang.String getAppPwd() {
		return get("app_pwd");
	}

	public void setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
	}

	public java.lang.String getAppCode() {
		return get("app_code");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setCredType(java.lang.String credType) {
		set("cred_type", credType);
	}

	public java.lang.String getCredType() {
		return get("cred_type");
	}

	public void setCredNo(java.lang.String credNo) {
		set("cred_no", credNo);
	}

	public java.lang.String getCredNo() {
		return get("cred_no");
	}

	public void setDecorationDate(java.util.Date decorationDate) {
		set("decoration_date", decorationDate);
	}

	public java.util.Date getDecorationDate() {
		return get("decoration_date");
	}

	public void setCheckinDate(java.util.Date checkinDate) {
		set("checkin_date", checkinDate);
	}

	public java.util.Date getCheckinDate() {
		return get("checkin_date");
	}

	public void setLiveStatus(java.lang.Integer liveStatus) {
		set("live_status", liveStatus);
	}

	public java.lang.Integer getLiveStatus() {
		return get("live_status");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setCredIssuer(java.lang.String credIssuer) {
		set("cred_issuer", credIssuer);
	}

	public java.lang.String getCredIssuer() {
		return get("cred_issuer");
	}

	public void setCredAddress(java.lang.String credAddress) {
		set("cred_address", credAddress);
	}

	public java.lang.String getCredAddress() {
		return get("cred_address");
	}

	public void setTmpOwnerNum(java.lang.String tmpOwnerNum) {
		set("tmp_owner_num", tmpOwnerNum);
	}

	public java.lang.String getTmpOwnerNum() {
		return get("tmp_owner_num");
	}

	public void setTmpUpdateTime(java.util.Date tmpUpdateTime) {
		set("tmp_update_time", tmpUpdateTime);
	}

	public java.util.Date getTmpUpdateTime() {
		return get("tmp_update_time");
	}

	public void setTaxType(java.lang.Integer taxType) {
		set("tax_type", taxType);
	}

	public java.lang.Integer getTaxType() {
		return get("tax_type");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

	public void setWxOpenid(java.lang.String wxOpenid) {
		set("wx_openId", wxOpenid);
	}

	public java.lang.String getWxOpenid() {
		return get("wx_openId");
	}

	public void setHeadPortraits(java.lang.String headPortraits) {
		set("head_portraits", headPortraits);
	}

	public java.lang.String getHeadPortraits() {
		return get("head_portraits");
	}

	public void setAppUsername(java.lang.String appUsername) {
		set("app_username", appUsername);
	}

	public java.lang.String getAppUsername() {
		return get("app_username");
	}

	public void setWxCode(java.lang.String wxCode) {
		set("wx_code", wxCode);
	}

	public java.lang.String getWxCode() {
		return get("wx_code");
	}

}
