package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProCharge<M extends BaseProCharge<M>> extends Model<M> implements IBean {

	public void setChargeId(java.lang.Long chargeId) {
		set("charge_id", chargeId);
	}

	public java.lang.Long getChargeId() {
		return get("charge_id");
	}

	public void setChargeNum(java.lang.String chargeNum) {
		set("charge_num", chargeNum);
	}

	public java.lang.String getChargeNum() {
		return get("charge_num");
	}

	public void setChargeName(java.lang.String chargeName) {
		set("charge_name", chargeName);
	}

	public java.lang.String getChargeName() {
		return get("charge_name");
	}

	public void setChargeType(java.lang.String chargeType) {
		set("charge_type", chargeType);
	}

	public java.lang.String getChargeType() {
		return get("charge_type");
	}

	public void setChargeCategory(java.lang.String chargeCategory) {
		set("charge_category", chargeCategory);
	}

	public java.lang.String getChargeCategory() {
		return get("charge_category");
	}

	public void setPrintOrder(java.lang.String printOrder) {
		set("print_order", printOrder);
	}

	public java.lang.String getPrintOrder() {
		return get("print_order");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setSubjectNo(java.lang.String subjectNo) {
		set("subject_no", subjectNo);
	}

	public java.lang.String getSubjectNo() {
		return get("subject_no");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

	public void setByName(java.lang.String byName) {
		set("by_name", byName);
	}

	public java.lang.String getByName() {
		return get("by_name");
	}

	public void setGroupIdent(java.lang.String groupIdent) {
		set("group_ident", groupIdent);
	}

	public java.lang.String getGroupIdent() {
		return get("group_ident");
	}

	public void setNotifyGroupIdent(java.lang.String notifyGroupIdent) {
		set("notify_group_ident", notifyGroupIdent);
	}

	public java.lang.String getNotifyGroupIdent() {
		return get("notify_group_ident");
	}

	public void setIsDeposit(java.lang.Integer isDeposit) {
		set("is_deposit", isDeposit);
	}

	public java.lang.Integer getIsDeposit() {
		return get("is_deposit");
	}

}
