package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogTaskDetail<M extends BaseLogTaskDetail<M>> extends Model<M> implements IBean {

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setIsShare(java.lang.Integer isShare) {
		set("is_share", isShare);
	}

	public java.lang.Integer getIsShare() {
		return get("is_share");
	}

	public void setExecTime(java.util.Date execTime) {
		set("exec_time", execTime);
	}

	public java.util.Date getExecTime() {
		return get("exec_time");
	}

	public void setExecYm(java.lang.Integer execYm) {
		set("exec_ym", execYm);
	}

	public java.lang.Integer getExecYm() {
		return get("exec_ym");
	}

	public void setIsUpdateAmount(java.lang.Integer isUpdateAmount) {
		set("is_update_amount", isUpdateAmount);
	}

	public java.lang.Integer getIsUpdateAmount() {
		return get("is_update_amount");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
