package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinLaundryList<M extends BaseFinLaundryList<M>> extends Model<M> implements IBean {

	public void setLaundryId(java.lang.Long laundryId) {
		set("laundry_id", laundryId);
	}

	public java.lang.Long getLaundryId() {
		return get("laundry_id");
	}

	public void setPayType(java.lang.Long payType) {
		set("pay_type", payType);
	}

	public java.lang.Long getPayType() {
		return get("pay_type");
	}

	public void setOrigin(java.lang.String origin) {
		set("origin", origin);
	}

	public java.lang.String getOrigin() {
		return get("origin");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public void setBankCardName(java.lang.String bankCardName) {
		set("bank_card_name", bankCardName);
	}

	public java.lang.String getBankCardName() {
		return get("bank_card_name");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
