package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFinJournal<M extends BaseFinJournal<M>> extends Model<M> implements IBean {

	public void setJournal(java.lang.Long journal) {
		set("journal", journal);
	}

	public java.lang.Long getJournal() {
		return get("journal");
	}

	public void setTradeDire(java.lang.String tradeDire) {
		set("trade_dire", tradeDire);
	}

	public java.lang.String getTradeDire() {
		return get("trade_dire");
	}

	public void setAmt(java.math.BigDecimal amt) {
		set("amt", amt);
	}

	public java.math.BigDecimal getAmt() {
		return get("amt");
	}

	public void setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public void setSubNo(java.lang.String subNo) {
		set("sub_no", subNo);
	}

	public java.lang.String getSubNo() {
		return get("sub_no");
	}

	public void setAccountingDate(java.util.Date accountingDate) {
		set("accounting_date", accountingDate);
	}

	public java.util.Date getAccountingDate() {
		return get("accounting_date");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}

	public java.lang.String getNum() {
		return get("num");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

}
