package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProMetertype<M extends BaseProMetertype<M>> extends Model<M> implements IBean {

	public void setMeterTypeId(java.lang.Long meterTypeId) {
		set("meter_type_id", meterTypeId);
	}

	public java.lang.Long getMeterTypeId() {
		return get("meter_type_id");
	}

	public void setMeterTypeName(java.lang.String meterTypeName) {
		set("meter_type_name", meterTypeName);
	}

	public java.lang.String getMeterTypeName() {
		return get("meter_type_name");
	}

	public void setMeterNum(java.lang.String meterNum) {
		set("meter_num", meterNum);
	}

	public java.lang.String getMeterNum() {
		return get("meter_num");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setIsPublic(java.lang.String isPublic) {
		set("is_public", isPublic);
	}

	public java.lang.String getIsPublic() {
		return get("is_public");
	}

}
