package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysContractTemplate<M extends BaseSysContractTemplate<M>> extends Model<M> implements IBean {

	public void setContractTemplateId(java.lang.Long contractTemplateId) {
		set("contract_template_id", contractTemplateId);
	}

	public java.lang.Long getContractTemplateId() {
		return get("contract_template_id");
	}

	public void setTemplateType(java.lang.Integer templateType) {
		set("template_type", templateType);
	}

	public java.lang.Integer getTemplateType() {
		return get("template_type");
	}

	public void setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
	}

	public java.lang.String getTemplateName() {
		return get("template_name");
	}

	public void setTemplateContent(java.lang.String templateContent) {
		set("template_content", templateContent);
	}

	public java.lang.String getTemplateContent() {
		return get("template_content");
	}

	public void setTemplateVer(java.lang.Long templateVer) {
		set("template_ver", templateVer);
	}

	public java.lang.Long getTemplateVer() {
		return get("template_ver");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("is_delete");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setOperPer(java.lang.String operPer) {
		set("oper_per", operPer);
	}

	public java.lang.String getOperPer() {
		return get("oper_per");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
