package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChargeStep<M extends BaseChargeStep<M>> extends Model<M> implements IBean {

	public void setChargeStepId(java.lang.Long chargeStepId) {
		set("charge_step_id", chargeStepId);
	}

	public java.lang.Long getChargeStepId() {
		return get("charge_step_id");
	}

	public void setDetailId(java.lang.Long detailId) {
		set("detail_id", detailId);
	}

	public java.lang.Long getDetailId() {
		return get("detail_id");
	}

	public void setFileCode(java.lang.Integer fileCode) {
		set("file_code", fileCode);
	}

	public java.lang.Integer getFileCode() {
		return get("file_code");
	}

	public void setMinValue(java.lang.Integer minValue) {
		set("min_value", minValue);
	}

	public java.lang.Integer getMinValue() {
		return get("min_value");
	}

	public void setMaxValue(java.lang.Integer maxValue) {
		set("max_value", maxValue);
	}

	public java.lang.Integer getMaxValue() {
		return get("max_value");
	}

	public void setStepPrice(java.math.BigDecimal stepPrice) {
		set("step_price", stepPrice);
	}

	public java.math.BigDecimal getStepPrice() {
		return get("step_price");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

}
