package com.sdj.rent.models.data.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIncurExpense<M extends BaseIncurExpense<M>> extends Model<M> implements IBean {

	public void setIncurId(java.lang.Integer incurId) {
		set("incur_id", incurId);
	}

	public java.lang.Integer getIncurId() {
		return get("incur_id");
	}

	public void setBatchNo(java.lang.String batchNo) {
		set("batch_no", batchNo);
	}

	public java.lang.String getBatchNo() {
		return get("batch_no");
	}

	public void setExpenseType(java.lang.String expenseType) {
		set("expense_type", expenseType);
	}

	public java.lang.String getExpenseType() {
		return get("expense_type");
	}

	public void setExpenseValue(java.lang.String expenseValue) {
		set("expense_value", expenseValue);
	}

	public java.lang.String getExpenseValue() {
		return get("expense_value");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOperId(java.lang.Integer operId) {
		set("oper_id", operId);
	}

	public java.lang.Integer getOperId() {
		return get("oper_id");
	}

	public void setOperDate(java.util.Date operDate) {
		set("oper_date", operDate);
	}

	public java.util.Date getOperDate() {
		return get("oper_date");
	}

	public void setProId(java.lang.Long proId) {
		set("pro_id", proId);
	}

	public java.lang.Long getProId() {
		return get("pro_id");
	}

	public void setIsDelete(java.lang.Long isDelete) {
		set("is_delete", isDelete);
	}

	public java.lang.Long getIsDelete() {
		return get("is_delete");
	}

}
