package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseBankOffer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankOffer extends BaseBankOffer<BankOffer> {
	public static final BankOffer dao = new BankOffer().dao();
}
