package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarAttachment extends BaseCarAttachment<CarAttachment> {
	public static final CarAttachment dao = new CarAttachment().dao();
}
