package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarCard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarCard extends BaseCarCard<CarCard> {
	public static final CarCard dao = new CarCard().dao();
}
