package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarGarage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarGarage extends BaseCarGarage<CarGarage> {
	public static final CarGarage dao = new CarGarage().dao();
}
