package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarInOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarInOut extends BaseCarInOut<CarInOut> {
	public static final CarInOut dao = new CarInOut().dao();
}
