package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarPosition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarPosition extends BaseCarPosition<CarPosition> {
	public static final CarPosition dao = new CarPosition().dao();
}
