package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseCarPayRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarPayRecord extends BaseCarPayRecord<CarPayRecord> {
	public static final CarPayRecord dao = new CarPayRecord().dao();
}
