package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseChargeStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeStep extends BaseChargeStep<ChargeStep> {
	public static final ChargeStep dao = new ChargeStep().dao();
}
