package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseChargeDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeDetail extends BaseChargeDetail<ChargeDetail> {
	public static final ChargeDetail dao = new ChargeDetail().dao();
}
