package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseChargeTradeDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChargeTradeDetail extends BaseChargeTradeDetail<ChargeTradeDetail> {
	public static final ChargeTradeDetail dao = new ChargeTradeDetail().dao();
}
