package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseContractRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractRoom extends BaseContractRoom<ContractRoom> {
	public static final ContractRoom dao = new ContractRoom().dao();
}
