package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinBankAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinBankAccount extends BaseFinBankAccount<FinBankAccount> {
	public static final FinBankAccount dao = new FinBankAccount().dao();
}
