package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinJournal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinJournal extends BaseFinJournal<FinJournal> {
	public static final FinJournal dao = new FinJournal().dao();
}
