package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinLaundryList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinLaundryList extends BaseFinLaundryList<FinLaundryList> {
	public static final FinLaundryList dao = new FinLaundryList().dao();
}
