package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinPrepayCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinPrepayCharge extends BaseFinPrepayCharge<FinPrepayCharge> {
	public static final FinPrepayCharge dao = new FinPrepayCharge().dao();
}
