package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinPrepaidAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinPrepaidAccount extends BaseFinPrepaidAccount<FinPrepaidAccount> {
	public static final FinPrepaidAccount dao = new FinPrepaidAccount().dao();
}
