package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinPayRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinPayRecord extends BaseFinPayRecord<FinPayRecord> {
	public static final FinPayRecord dao = new FinPayRecord().dao();
}
