package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinRechargeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinRechargeRecord extends BaseFinRechargeRecord<FinRechargeRecord> {
	public static final FinRechargeRecord dao = new FinRechargeRecord().dao();
}
