package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinSubject extends BaseFinSubject<FinSubject> {
	public static final FinSubject dao = new FinSubject().dao();
}
