package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinTradeSummary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinTradeSummary extends BaseFinTradeSummary<FinTradeSummary> {
	public static final FinTradeSummary dao = new FinTradeSummary().dao();
}
