package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinTradeDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinTradeDetail extends BaseFinTradeDetail<FinTradeDetail> {
	public static final FinTradeDetail dao = new FinTradeDetail().dao();
}
