package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinTradeOverdue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinTradeOverdue extends BaseFinTradeOverdue<FinTradeOverdue> {
	public static final FinTradeOverdue dao = new FinTradeOverdue().dao();
}
