package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseFinTradeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinTradeRecord extends BaseFinTradeRecord<FinTradeRecord> {
	public static final FinTradeRecord dao = new FinTradeRecord().dao();
}
