package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseIncurExpense;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IncurExpense extends BaseIncurExpense<IncurExpense> {
	public static final IncurExpense dao = new IncurExpense().dao();
}
