package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseLogOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOperation extends BaseLogOperation<LogOperation> {
	public static final LogOperation dao = new LogOperation().dao();
}
