package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseLogTaskDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogTaskDetail extends BaseLogTaskDetail<LogTaskDetail> {
	public static final LogTaskDetail dao = new LogTaskDetail().dao();
}
