package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseMeterRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MeterRecord extends BaseMeterRecord<MeterRecord> {
	public static final MeterRecord dao = new MeterRecord().dao();
}
