package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseMsCrdbinInf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsCrdbinInf extends BaseMsCrdbinInf<MsCrdbinInf> {
	public static final MsCrdbinInf dao = new MsCrdbinInf().dao();
}
