package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseOptConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OptConfig extends BaseOptConfig<OptConfig> {
	public static final OptConfig dao = new OptConfig().dao();
}
