package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseOptMerchant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OptMerchant extends BaseOptMerchant<OptMerchant> {
	public static final OptMerchant dao = new OptMerchant().dao();
}
