package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseOrderRefundDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderRefundDetail extends BaseOrderRefundDetail<OrderRefundDetail> {
	public static final OrderRefundDetail dao = new OrderRefundDetail().dao();
}
