package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseOrderRefund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderRefund extends BaseOrderRefund<OrderRefund> {
	public static final OrderRefund dao = new OrderRefund().dao();
}
