package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProCharge extends BaseProCharge<ProCharge> {
	public static final ProCharge dao = new ProCharge().dao();
}
