package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProContract extends BaseProContract<ProContract> {
	public static final ProContract dao = new ProContract().dao();
}
