package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProDepartment extends BaseProDepartment<ProDepartment> {
	public static final ProDepartment dao = new ProDepartment().dao();
}
