package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProEmployee extends BaseProEmployee<ProEmployee> {
	public static final ProEmployee dao = new ProEmployee().dao();
}
