package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProGuestextend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProGuestextend extends BaseProGuestextend<ProGuestextend> {
	public static final ProGuestextend dao = new ProGuestextend().dao();
}
