package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProGuestbase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProGuestbase extends BaseProGuestbase<ProGuestbase> {
	public static final ProGuestbase dao = new ProGuestbase().dao();
}
