package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProHouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProHouse extends BaseProHouse<ProHouse> {
	public static final ProHouse dao = new ProHouse().dao();
}
