package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProMetertype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProMetertype extends BaseProMetertype<ProMetertype> {
	public static final ProMetertype dao = new ProMetertype().dao();
}
