package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProMeter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProMeter extends BaseProMeter<ProMeter> {
	public static final ProMeter dao = new ProMeter().dao();
}
