package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProMember extends BaseProMember<ProMember> {
	public static final ProMember dao = new ProMember().dao();
}
