package com.sdj.rent.models.data;

import java.util.Date;

import com.sdj.rent.models.data.base.BaseProManagement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProManagement extends BaseProManagement<ProManagement> {
	public static final ProManagement dao = new ProManagement().dao();
	
	public ProManagement()
	{
		this.setOperPer("admin");
		this.setOperDate(new Date());
	}
	
}
