package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProRoomDeposit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProRoomDeposit extends BaseProRoomDeposit<ProRoomDeposit> {
	public static final ProRoomDeposit dao = new ProRoomDeposit().dao();
}
