package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseProRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProRoom extends BaseProRoom<ProRoom> {
	public static final ProRoom dao = new ProRoom().dao();
}
