package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseRoomHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomHistory extends BaseRoomHistory<RoomHistory> {
	public static final RoomHistory dao = new RoomHistory().dao();
}
