package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseRoomGuest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomGuest extends BaseRoomGuest<RoomGuest> {
	public static final RoomGuest dao = new RoomGuest().dao();
}
