package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseRoomRentUpdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomRentUpdate extends BaseRoomRentUpdate<RoomRentUpdate> {
	public static final RoomRentUpdate dao = new RoomRentUpdate().dao();
}
