package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseRoomCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomCharge extends BaseRoomCharge<RoomCharge> {
	public static final RoomCharge dao = new RoomCharge().dao();
}
