package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseServiceOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServiceOrder extends BaseServiceOrder<ServiceOrder> {
	public static final ServiceOrder dao = new ServiceOrder().dao();
}
