package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareRuleMeter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareRuleMeter extends BaseShareRuleMeter<ShareRuleMeter> {
	public static final ShareRuleMeter dao = new ShareRuleMeter().dao();
}
