package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareHouseSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareHouseSetting extends BaseShareHouseSetting<ShareHouseSetting> {
	public static final ShareHouseSetting dao = new ShareHouseSetting().dao();
}
