package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareRoom extends BaseShareRoom<ShareRoom> {
	public static final ShareRoom dao = new ShareRoom().dao();
}
