package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareRecord extends BaseShareRecord<ShareRecord> {
	public static final ShareRecord dao = new ShareRecord().dao();
}
