package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareRuleManagement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareRuleManagement extends BaseShareRuleManagement<ShareRuleManagement> {
	public static final ShareRuleManagement dao = new ShareRuleManagement().dao();
}
