package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseShareRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareRule extends BaseShareRule<ShareRule> {
	public static final ShareRule dao = new ShareRule().dao();
}
