package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSmsRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsRecord extends BaseSmsRecord<SmsRecord> {
	public static final SmsRecord dao = new SmsRecord().dao();
}
