package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSmsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsTemplate extends BaseSmsTemplate<SmsTemplate> {
	public static final SmsTemplate dao = new SmsTemplate().dao();
}
