package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysChart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysChart extends BaseSysChart<SysChart> {
	public static final SysChart dao = new SysChart().dao();
}
