package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysContractTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysContractTemplate extends BaseSysContractTemplate<SysContractTemplate> {
	public static final SysContractTemplate dao = new SysContractTemplate().dao();
}
