package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysNotice extends BaseSysNotice<SysNotice> {
	public static final SysNotice dao = new SysNotice().dao();
}
