package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysPayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPayment extends BaseSysPayment<SysPayment> {
	public static final SysPayment dao = new SysPayment().dao();
}
