package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysRoleMenuFn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenuFn extends BaseSysRoleMenuFn<SysRoleMenuFn> {
	public static final SysRoleMenuFn dao = new SysRoleMenuFn().dao();
}
