package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole().dao();
}
