package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysRecMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRecMenu extends BaseSysRecMenu<SysRecMenu> {
	public static final SysRecMenu dao = new SysRecMenu().dao();
}
