package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleUser extends BaseSysRoleUser<SysRoleUser> {
	public static final SysRoleUser dao = new SysRoleUser().dao();
}
