package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenu extends BaseSysRoleMenu<SysRoleMenu> {
	public static final SysRoleMenu dao = new SysRoleMenu().dao();
}
