package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseSysSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSequence extends BaseSysSequence<SysSequence> {
	public static final SysSequence dao = new SysSequence().dao();
}
