package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseVariableCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VariableCopy extends BaseVariableCopy<VariableCopy> {
	public static final VariableCopy dao = new VariableCopy().dao();
}
