package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Variable extends BaseVariable<Variable> {
	public static final Variable dao = new Variable().dao();
}
