package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseWaterElecRac;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaterElecRac extends BaseWaterElecRac<WaterElecRac> {
	public static final WaterElecRac dao = new WaterElecRac().dao();
}
