package com.sdj.rent.models.data;

import com.sdj.rent.models.data.base.BaseWaterElecRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaterElecRecord extends BaseWaterElecRecord<WaterElecRecord> {
	public static final WaterElecRecord dao = new WaterElecRecord().dao();
}
